### ISSUE TITLE
2.3 Document

### ISSUE THREAD

**Issue by melaniephilipp** [w3c/wcag2ict#229] opened 2023-09-29 14:45 UTC
The double negative in note 4 is difficult to follow 
Note 4:  “...because that software is not providing a non-fully functioning presentation of that content.” 

Can you please clarify the statement?

**Comment by maryjom** [comment] 2023-10-02 21:36
Thank you for taking the time to review the WCAG2ICT public draft. Our task force will review your comment and develop a response that we hope will address your concern. The response will be drafted in a comment on this issue, marked **DRAFT RESPONSE** until the Task Force reaches consensus.

**Comment by mitchellevan** [comment] 2023-11-20 20:35
**DRAFT RESPONSE:**

Thanks for calling attention to this. The issue is in Note 4 here: https://www.w3.org/TR/2023/DNOTE-wcag2ict-20230815/#document

> A collection of files zipped together into an archive, stored within a single virtual hard drive file, or stored in a single "encrypted file system" file, do not constitute a single document. The software that archives/encrypts those files or manages the contents of the virtual hard drive does not function as a user agent for the individually collected files in that collection because that software is not providing a non-fully functioning presentation of that content.

In the second sentence the double negative is a typo. To make the sentence accurate we could change "non-fully functioning" to "fully functioning".

However, the second sentence is not actually important for the meaning of a "collection" of files. Suppose a file system manager application did provide a fully-functioning presentation (e.g., a robust preview) of individual files within a virtual file system. This would mean the file system manager is a user agent, yet the virtual file system file would still be a "collection" not a "document."

Therefore, we will remove the second sentence. Note 4 will be as follows:

> A collection of files zipped together into an archive, stored within a single virtual hard drive file, or stored in a single "encrypted file system" file do not constitute a single document.

**Comment by maryjom** [comment] 2024-01-16 19:51
The sentence was removed and the changes have been merged into the editor's draft, so this can be closed.

**Closed by maryjom** 2024-01-16 19:51 UTC
Labels: Public Comment, FPWD, Editorial, TF answer completed
